"""Document strings in the two PDF locales: English (uk/default) and Persian (ir).

PDFs render in exactly one of these per the company's locale; the app UI i18n
(en/fa/es/ar) is separate.
"""
from __future__ import annotations

EN = {
    "invoice": "INVOICE",
    "time_invoice": "INVOICE",
    "receipt": "RECEIPT",
    "statement": "ACCOUNT STATEMENT",
    "purchase_order": "PURCHASE ORDER",
    "payslip": "PAYSLIP",
    "from": "From",
    "bill_to": "Bill To",
    "supplier": "Supplier",
    "employee": "Employee",
    "number": "No.",
    "issue_date": "Issue date",
    "due_date": "Due date",
    "date": "Date",
    "status": "Status",
    "period": "Period",
    "pay_period": "Pay period",
    "po_reference": "PO reference",
    "description": "Description",
    "qty": "Qty",
    "hours": "Hours",
    "rate": "Rate",
    "unit_price": "Unit price",
    "tax": "Tax",
    "amount": "Amount",
    "subtotal": "Subtotal",
    "discount": "Discount",
    "total": "Total",
    "amount_payable": "Amount payable",
    "amount_paid": "Amount paid",
    "balance_due": "Balance due",
    "net_pay": "Net pay",
    "gross_pay": "Gross pay",
    "deductions": "Deductions",
    "amount_in_words": "Amount in words",
    "how_to_pay": "How to pay",
    "payment_terms": "Payment terms",
    "tax_id": "Tax ID / VAT",
    "reg_no": "Reg. no.",
    "signature": "Signature",
    "stamp": "Stamp",
    "page": "Page",
    "tel": "Tel",
    "email": "Email",
    "web": "Web",
    "received_with_thanks": "Received with thanks",
    "opening_balance": "Opening balance",
    "closing_balance": "Closing balance",
    "debit": "Debit",
    "credit": "Credit",
    "balance": "Balance",
}

FA = {
    "invoice": "صورتحساب",
    "time_invoice": "صورتحساب",
    "receipt": "رسید",
    "statement": "صورت‌حساب دوره‌ای",
    "purchase_order": "سفارش خرید",
    "payslip": "فیش حقوقی",
    "from": "از",
    "bill_to": "صورتحساب برای",
    "supplier": "تأمین‌کننده",
    "employee": "کارمند",
    "number": "شماره",
    "issue_date": "تاریخ صدور",
    "due_date": "سررسید",
    "date": "تاریخ",
    "status": "وضعیت",
    "period": "دوره",
    "pay_period": "دوره پرداخت",
    "po_reference": "شماره سفارش",
    "description": "شرح",
    "qty": "تعداد",
    "hours": "ساعت",
    "rate": "نرخ",
    "unit_price": "قیمت واحد",
    "tax": "مالیات",
    "amount": "مبلغ",
    "subtotal": "جمع جزء",
    "discount": "تخفیف",
    "total": "جمع کل",
    "amount_payable": "مبلغ قابل پرداخت",
    "amount_paid": "مبلغ پرداختی",
    "balance_due": "مانده بدهی",
    "net_pay": "خالص پرداختی",
    "gross_pay": "ناخالص حقوق",
    "deductions": "کسورات",
    "amount_in_words": "مبلغ به حروف",
    "how_to_pay": "نحوه پرداخت",
    "payment_terms": "شرایط پرداخت",
    "tax_id": "شناسه مالیاتی",
    "reg_no": "شماره ثبت",
    "signature": "امضا",
    "stamp": "مهر",
    "page": "صفحه",
    "tel": "تلفن",
    "email": "ایمیل",
    "web": "وب‌سایت",
    "received_with_thanks": "با تشکر دریافت شد",
    "opening_balance": "مانده ابتدای دوره",
    "closing_balance": "مانده پایان دوره",
    "debit": "بدهکار",
    "credit": "بستانکار",
    "balance": "مانده",
}


def labels_for(locale: str | None) -> dict:
    return FA if (locale or "").lower() == "ir" else EN
